# Generated by Django 4.2.16 on 2026-04-03 09:06

from django.db import migrations, models
import tienda.models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualización',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=tienda.models.producto_image_upload_to),
        ),
    ]
